from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QGridLayout, QFormLayout, QFrame,
    QLabel, QPushButton, QComboBox, QLineEdit, QSpinBox, QDoubleSpinBox,
    QCheckBox, QTableWidget, QTableWidgetItem, QPlainTextEdit, QTabWidget,
    QHeaderView, QStackedWidget, QStatusBar, QSplitter, QSizePolicy, QScrollArea
)


def build_ui(window):
    """Build the feature-based interface without changing reader commands."""
    root = QWidget()
    outer = QVBoxLayout(root)
    outer.setContentsMargins(14, 12, 14, 10)
    outer.setSpacing(10)

    top = window.card()
    header = QGridLayout(top)
    header.setContentsMargins(16, 12, 16, 12)
    header.setHorizontalSpacing(12)
    title_box = QVBoxLayout()
    title = QLabel("RFID Reader")
    title.setObjectName("Title")
    title.setToolTip("RFID Reader")
    subtitle = QLabel("STM32 host interface - reliable serialized transactions")
    subtitle.setObjectName("Sub")
    title_box.addWidget(title)
    title_box.addWidget(subtitle)
    header.addLayout(title_box, 0, 0, 2, 1)
    header.addWidget(QLabel("COM Port"), 0, 1)
    window.port = QComboBox()
    window.port.setMinimumWidth(260)
    header.addWidget(window.port, 0, 2)
    header.addWidget(QLabel("Baud"), 1, 1)
    window.baud = QComboBox()
    for value in (115200, 57600, 38400, 19200, 9600):
        window.baud.addItem(str(value), value)
    header.addWidget(window.baud, 1, 2)
    window.connect = QPushButton("Connect")
    window.connect.setObjectName("Accent")
    window.connect.clicked.connect(window.toggle)
    header.addWidget(window.connect, 0, 3, 2, 1)
    window.conn = QLabel("Disconnected")
    window.conn.setStyleSheet("color:#C34C56;font-weight:700")
    header.addWidget(window.conn, 0, 4, 2, 1)
    window.theme_btn = QPushButton()
    window.theme_btn.clicked.connect(lambda: window.set_theme(not window.dark))
    header.addWidget(window.theme_btn, 0, 5, 2, 1)
    header.setColumnStretch(6, 1)
    outer.addWidget(top)

    kpis = QHBoxLayout()
    kpis.setSpacing(8)
    window.kv = []
    for label, value in (
        ("Reader", "Offline"), ("Inventory", "IDLE"),
        ("Total Reads", "0"), ("Unique EPCs", "0"),
        ("Read Rate", "0.0/s"), ("Temperature", "--")
    ):
        card = window.card()
        layout = QVBoxLayout(card)
        value_label = QLabel(value)
        value_label.setObjectName("Value")
        caption = QLabel(label)
        caption.setObjectName("Caption")
        layout.addWidget(value_label)
        layout.addWidget(caption)
        kpis.addWidget(card)
        window.kv.append(value_label)
    outer.addLayout(kpis)

    body = QHBoxLayout()
    body.setSpacing(10)
    nav = window.card()
    nav.setObjectName("NavCard")
    nav.setFixedWidth(222)
    nav_layout = QVBoxLayout(nav)
    nav_layout.setContentsMargins(10, 12, 10, 12)
    nav_layout.setSpacing(5)
    nav_title = QLabel("READER TOOLS")
    nav_title.setObjectName("Caption")
    nav_layout.addWidget(nav_title)
    nav_hint = QLabel("Select a workspace.")
    nav_hint.setObjectName("Sub")
    nav_hint.setWordWrap(True)
    nav_layout.addWidget(nav_hint)
    nav_layout.addSpacing(8)

    window.nav_buttons = []
    features = [
        ("Reader Control", "Single and multi polling"),
        ("Reader Settings", "Region, antenna, power"),
        ("Reader Information", "Read device details"),
        ("Tag Filter", "Limit visible EPC rows"),
        ("Tag Read", "Read tag memory"),
        ("Tag Write", "Write tag memory"),
        ("Interface", "Display preferences"),
        ("Tag Lock/Kill", "Lock or kill a tag"),
    ]
    for index, (label, hint) in enumerate(features):
        button = QPushButton(label)
        button.setObjectName("NavButton")
        button.setCheckable(True)
        button.setToolTip(hint)
        button.clicked.connect(
            lambda checked=False, page_index=index: window.select_feature(page_index)
        )
        nav_layout.addWidget(button)
        window.nav_buttons.append(button)
    nav_layout.addStretch()
    body.addWidget(nav)

    window.stack = QStackedWidget()
    feature_scroll = QScrollArea()
    feature_scroll.setFrameShape(QFrame.NoFrame)
    feature_scroll.setWidgetResizable(True)
    feature_scroll.setWidget(window.stack)
    window.main_split = QSplitter(Qt.Horizontal)
    window.main_split.setChildrenCollapsible(False)
    window.main_split.addWidget(feature_scroll)

    content_column = QWidget()
    window.content_layout = QVBoxLayout(content_column)
    window.content_layout.setContentsMargins(0, 0, 0, 0)
    window.content_layout.setSpacing(8)
    body.addWidget(content_column, 1)
    outer.addLayout(body, 1)
    window.setCentralWidget(root)
    window.setStatusBar(QStatusBar())

    # Inventory stays visible while feature workspaces change above it.
    inventory_card = window.card()
    inventory_layout = QVBoxLayout(inventory_card)
    inventory_layout.addWidget(window.sec("Inventory Overview"))
    inventory_bar = QHBoxLayout()
    clear_button = QPushButton("Clear")
    clear_button.clicked.connect(window.clear_inv)
    export_button = QPushButton("Export CSV")
    export_button.clicked.connect(window.export_csv)
    refresh_button = QPushButton("Refresh Reader Info")
    refresh_button.clicked.connect(window.request_info)
    window.hint = QLabel("Waiting for TAG frames...")
    window.hint.setObjectName("Sub")
    for button in (clear_button, export_button, refresh_button):
        inventory_bar.addWidget(button)
    inventory_bar.addStretch()
    inventory_bar.addWidget(window.hint)
    inventory_layout.addLayout(inventory_bar)
    window.table = QTableWidget(0, 6)
    window.table.setHorizontalHeaderLabels(
        ["Time", "EPC", "RSSI (dBm)", "Antenna", "Frequency (kHz)", "Reads"]
    )
    window.table.setAlternatingRowColors(True)
    window.table.setSelectionBehavior(QTableWidget.SelectRows)
    window.table.verticalHeader().setVisible(False)
    window.table.itemSelectionChanged.connect(window.use_selected_epc)
    table_header = window.table.horizontalHeader()
    table_header.setSectionResizeMode(0, QHeaderView.ResizeToContents)
    table_header.setSectionResizeMode(1, QHeaderView.Stretch)
    for column in (2, 3, 4, 5):
        table_header.setSectionResizeMode(column, QHeaderView.ResizeToContents)
    inventory_layout.addWidget(window.table)
    window.main_split.addWidget(inventory_card)
    window.main_split.setStretchFactor(0, 2)
    window.main_split.setStretchFactor(1, 1)
    window.main_split.setSizes([700, 350])

    # Reader Control
    control_page = QWidget()
    control_layout = QVBoxLayout(control_page)
    control_layout.setContentsMargins(0, 0, 0, 0)
    control_layout.setSpacing(10)
    control_card = window.card()
    control_card_layout = QVBoxLayout(control_card)
    control_card_layout.addWidget(window.sec("Reader Control"))
    control_intro = QLabel("Start a one-shot read or keep inventory running until you stop it.")
    control_intro.setObjectName("Sub")
    control_card_layout.addWidget(control_intro)
    control_grid = QGridLayout()
    window.single = QPushButton("Single Poll")
    window.single.setObjectName("Primary")
    window.multi = QPushButton("Multi Poll")
    window.multi.setObjectName("Primary")
    window.stop = QPushButton("Stop")
    window.stop.setObjectName("Danger")
    window.resume = QPushButton("Resume Multi")
    window.single.clicked.connect(window.single_poll)
    window.multi.clicked.connect(window.multi_poll)
    window.stop.clicked.connect(window.stop_inv)
    window.resume.clicked.connect(window.multi_poll)
    control_grid.addWidget(window.single, 0, 0)
    control_grid.addWidget(window.multi, 0, 1)
    control_grid.addWidget(window.stop, 1, 0)
    control_grid.addWidget(window.resume, 1, 1)
    control_grid.addWidget(QLabel("Single poll timeout"), 2, 0)
    window.poll_timeout = QDoubleSpinBox()
    window.poll_timeout.setRange(0.5, 30.0)
    window.poll_timeout.setSingleStep(0.5)
    window.poll_timeout.setValue(3.0)
    window.poll_timeout.setSuffix(" s")
    control_grid.addWidget(window.poll_timeout, 2, 1)
    control_card_layout.addLayout(control_grid)
    control_layout.addWidget(control_card)
    polling_note = window.card()
    polling_note_layout = QVBoxLayout(polling_note)
    polling_note_layout.addWidget(window.sec("Polling behavior"))
    note = QLabel(
        "Single Poll sends the existing START/STOP host protocol around one tag read. "
        "Multi Poll sends START and leaves inventory active until Stop."
    )
    note.setWordWrap(True)
    note.setObjectName("Sub")
    polling_note_layout.addWidget(note)
    control_layout.addWidget(polling_note)
    control_layout.addStretch()
    window.stack.addWidget(control_page)

    # Reader Settings
    settings_page = QWidget()
    settings_layout = QVBoxLayout(settings_page)
    settings_layout.setContentsMargins(0, 0, 0, 0)
    settings_card = window.card()
    settings_form = QFormLayout(settings_card)
    settings_form.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow)
    settings_form.addRow(window.sec("Reader Settings"))
    settings_help = QLabel(
        "Change reader configuration and send only the corresponding existing SET command."
    )
    settings_help.setObjectName("Sub")
    settings_help.setWordWrap(True)
    settings_form.addRow(settings_help)
    window.region = QLineEdit("01")
    window.region.setMaxLength(2)
    settings_form.addRow("Region (hex)", window.region)
    window.tx = QSpinBox()
    window.tx.setRange(1, 255)
    window.tx.setValue(1)
    settings_form.addRow("TX antenna", window.tx)
    window.rx = QSpinBox()
    window.rx.setRange(1, 255)
    window.rx.setValue(1)
    settings_form.addRow("RX antenna", window.rx)
    window.power = QDoubleSpinBox()
    window.power.setRange(0.0, 33.0)
    window.power.setDecimals(2)
    window.power.setSingleStep(0.25)
    window.power.setValue(30.0)
    window.power.setSuffix(" dBm")
    window.power.setToolTip("Transmit power in dBm. Firmware sends centi-dBm.")
    settings_form.addRow("Power", window.power)
    window.session = QSpinBox()
    window.session.setRange(0, 3)
    settings_form.addRow("Session", window.session)
    settings_actions_layout = QHBoxLayout()
    settings_actions = [
        ("Set Power", lambda: window.enqueue(
            f"SET_POWER,{int(round(window.power.value() * 100.0))}"
        )),
        ("Set Antenna", lambda: window.enqueue(
            f"SET_ANTENNA,{window.tx.value()},{window.rx.value()}"
        )),
        ("Set Region", window.set_region),
        ("Set Session", lambda: window.enqueue(f"SET_SESSION,{window.session.value()}")),
    ]
    for label, handler in settings_actions:
        button = QPushButton(label)
        button.clicked.connect(handler)
        settings_actions_layout.addWidget(button)
    settings_form.addRow("", settings_actions_layout)
    settings_layout.addWidget(settings_card)
    settings_layout.addStretch()
    window.stack.addWidget(settings_page)

    # Reader Information
    information_page = QWidget()
    information_layout = QVBoxLayout(information_page)
    information_layout.setContentsMargins(0, 0, 0, 0)
    information_card = window.card()
    information_grid = QGridLayout(information_card)
    information_grid.setContentsMargins(18, 18, 18, 18)
    information_grid.addWidget(window.sec("Reader Information"), 0, 0, 1, 2)
    information_help = QLabel(
        "Query one device value at a time. Requests remain serialized through the existing command queue."
    )
    information_help.setObjectName("Sub")
    information_help.setWordWrap(True)
    information_grid.addWidget(information_help, 1, 0, 1, 2)
    information_actions = [
        ("Version", "GET_VERSION"), ("Serial", "GET_SERIAL"),
        ("Temperature", "GET_TEMPERATURE"), ("Region", "GET_REGION"),
        ("Antenna", "GET_ANTENNA"), ("Power", "GET_POWER"),
        ("Protocol", "GET_PROTOCOL"), ("Session", "GET_SESSION"),
        ("Frequency", "GET_FREQUENCY"), ("Regions", "GET_REGIONS"),
    ]
    for index, (label, command) in enumerate(information_actions):
        button = QPushButton(label)
        button.clicked.connect(lambda checked=False, cmd=command: window.request(cmd))
        information_grid.addWidget(button, 2 + index // 2, index % 2)
    information_layout.addWidget(information_card)
    information_layout.addStretch()
    window.stack.addWidget(information_page)

    # Tag Filter
    filter_page = QWidget()
    filter_layout = QVBoxLayout(filter_page)
    filter_layout.setContentsMargins(0, 0, 0, 0)
    filter_card = window.card()
    filter_form = QFormLayout(filter_card)
    filter_form.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow)
    filter_form.addRow(window.sec("Tag Filter"))
    filter_help = QLabel(
        "Filtering is local to this interface; it does not change what the reader captures."
    )
    filter_help.setObjectName("Sub")
    filter_help.setWordWrap(True)
    filter_form.addRow(filter_help)
    window.filter_edit = QLineEdit()
    window.filter_edit.setPlaceholderText("Filter EPC by text or hex")
    window.filter_edit.textChanged.connect(window.apply_filter)
    filter_form.addRow("EPC contains", window.filter_edit)
    filter_actions = QHBoxLayout()
    window.filter_exact_cb = QCheckBox("Exact match")
    window.filter_exact_cb.toggled.connect(window.apply_filter)
    clear_filter = QPushButton("Clear Filter")
    clear_filter.clicked.connect(window.clear_filter)
    filter_actions.addWidget(window.filter_exact_cb)
    filter_actions.addStretch()
    filter_actions.addWidget(clear_filter)
    filter_form.addRow("", filter_actions)
    filter_layout.addWidget(filter_card)
    filter_layout.addStretch()
    window.stack.addWidget(filter_page)

    # Tag Read
    read_page = QWidget()
    read_layout = QVBoxLayout(read_page)
    read_layout.setContentsMargins(0, 0, 0, 0)
    read_card = window.card()
    read_form = QFormLayout(read_card)
    read_form.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow)
    read_form.addRow(window.sec("Tag Read"))
    read_help = QLabel(
        "Select an inventory row or enter an EPC, then read words from the selected memory bank."
    )
    read_help.setObjectName("Sub")
    read_help.setWordWrap(True)
    read_form.addRow(read_help)
    window.read_target_epc = QLineEdit()
    window.read_target_epc.setPlaceholderText("Select a tag row to target it automatically")
    read_form.addRow("Target EPC", window.read_target_epc)
    window.read_bank = QComboBox()
    window.read_bank.addItem("TID (2)", 2)
    window.read_bank.addItem("USER (3)", 3)
    window.read_bank.addItem("EPC (1)", 1)
    window.read_bank.addItem("RESERVED (0)", 0)
    window.read_bank.setCurrentIndex(0)
    read_form.addRow("Memory bank", window.read_bank)
    window.read_address = QSpinBox()
    window.read_address.setRange(0, 2147483647)
    window.read_address.setValue(0)
    read_form.addRow("Start word address", window.read_address)
    window.read_words = QSpinBox()
    window.read_words.setRange(1, 96)
    window.read_words.setValue(2)
    read_form.addRow("Word count", window.read_words)
    read_actions = QHBoxLayout()
    window.read_use_selected = QPushButton("Use Selected EPC")
    window.read_use_selected.clicked.connect(window.use_selected_read_epc)
    window.read_tag_btn = QPushButton("Read Tag")
    window.read_tag_btn.setObjectName("Primary")
    window.read_tag_btn.clicked.connect(window.read_tag)
    read_actions.addWidget(window.read_use_selected)
    read_actions.addWidget(window.read_tag_btn)
    read_form.addRow("", read_actions)
    window.read_result = QLineEdit()
    window.read_result.setReadOnly(True)
    window.read_result.setPlaceholderText("Read data will appear here")
    read_form.addRow("Last data", window.read_result)
    read_layout.addWidget(read_card)
    read_layout.addStretch()
    window.stack.addWidget(read_page)

    # Tag Write
    write_page = QWidget()
    write_layout = QVBoxLayout(write_page)
    write_layout.setContentsMargins(0, 0, 0, 0)
    write_card = window.card()
    write_form = QFormLayout(write_card)
    write_form.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow)
    write_form.addRow(window.sec("Tag Write"))
    write_help = QLabel(
        "Choose tag memory writing or EPC editing. Writes are disabled while inventory is running and require confirmation before the backend command is sent."
    )
    write_help.setObjectName("Sub")
    write_help.setWordWrap(True)
    write_form.addRow(write_help)
    window.write_operation = QComboBox()
    window.write_operation.addItem("Tag Data Write", "TAG_DATA")
    window.write_operation.addItem("EPC Editing / EPC Write", "EPC_EDIT")
    window.write_operation.currentIndexChanged.connect(window.update_write_mode)
    write_form.addRow("Operation", window.write_operation)

    window.write_target_label = QLabel("Target EPC")
    window.target_epc = QLineEdit()
    window.target_epc.setPlaceholderText("Current EPC (select a tag row to fill)")
    write_form.addRow(window.write_target_label, window.target_epc)

    window.epc_edit_old_label = QLabel("Current EPC")
    window.epc_edit_old = QLineEdit()
    window.epc_edit_old.setReadOnly(True)
    window.epc_edit_old.setPlaceholderText("Select a tag row first")
    write_form.addRow(window.epc_edit_old_label, window.epc_edit_old)
    window.epc_edit_new_label = QLabel("New EPC")
    window.epc_edit_new = QLineEdit()
    window.epc_edit_new.setPlaceholderText("Hex EPC, even number of digits")
    write_form.addRow(window.epc_edit_new_label, window.epc_edit_new)

    window.write_bank_label = QLabel("Memory bank")
    window.write_bank = QComboBox()
    window.write_bank.addItem("USER (3)", 3)
    window.write_bank.addItem("EPC (1)", 1)
    window.write_bank.addItem("TID (2)", 2)
    window.write_bank.addItem("RESERVED (0)", 0)
    write_form.addRow(window.write_bank_label, window.write_bank)
    window.write_address_label = QLabel("Start word address")
    window.write_address = QSpinBox()
    window.write_address.setRange(0, 2147483647)
    window.write_address.setValue(0)
    write_form.addRow(window.write_address_label, window.write_address)
    window.write_data_label = QLabel("Write data")
    window.write_data = QLineEdit()
    window.write_data.setPlaceholderText("Hex data, even number of digits (max 64 bytes)")
    write_form.addRow(window.write_data_label, window.write_data)
    window.write_access_password_label = QLabel("Access Password")
    window.write_access_password = QLineEdit("00000000")
    window.write_access_password.setEchoMode(QLineEdit.Password)
    window.write_access_password.setMaxLength(8)
    window.write_access_password.setPlaceholderText("8 hexadecimal characters")
    write_form.addRow(window.write_access_password_label, window.write_access_password)
    write_actions = QHBoxLayout()
    window.use_selected = QPushButton("Use Selected EPC")
    window.use_selected.clicked.connect(window.use_selected_epc)
    window.write_tag_btn = QPushButton("Write Tag Data")
    window.write_tag_btn.setObjectName("Primary")
    window.write_tag_btn.clicked.connect(window.write_selected_operation)
    write_actions.addWidget(window.use_selected)
    write_actions.addWidget(window.write_tag_btn)
    write_form.addRow("", write_actions)
    window.update_write_mode()
    write_layout.addWidget(write_card)
    write_layout.addStretch()
    window.stack.addWidget(write_page)

    # Interface
    interface_page = QWidget()
    interface_layout = QVBoxLayout(interface_page)
    interface_layout.setContentsMargins(0, 0, 0, 0)
    interface_card = window.card()
    interface_card_layout = QVBoxLayout(interface_card)
    interface_card_layout.addWidget(window.sec("Interface"))
    interface_help = QLabel("These options affect the local display and reconnect behavior only.")
    interface_help.setObjectName("Sub")
    interface_help.setWordWrap(True)
    interface_card_layout.addWidget(interface_help)
    window.dedupe = QCheckBox("One row per EPC (always)")
    window.dedupe.setChecked(True)
    window.dedupe.setEnabled(False)
    window.auto = QCheckBox("Auto-scroll inventory")
    window.auto.setChecked(True)
    window.clear_start = QCheckBox("Clear inventory on START")
    window.reconnect = QCheckBox("Auto reconnect")
    window.reconnect.setChecked(True)
    for option in (window.dedupe, window.auto, window.clear_start, window.reconnect):
        interface_card_layout.addWidget(option)
    interface_layout.addWidget(interface_card)
    interface_layout.addStretch()
    window.stack.addWidget(interface_page)

    # Tag Lock/Kill
    tag_lock_kill_page = QWidget()
    tag_lock_kill_layout = QVBoxLayout(tag_lock_kill_page)
    tag_lock_kill_layout.setContentsMargins(0, 0, 0, 0)
    tag_lock_kill_card = window.card()
    tag_lock_kill_form = QFormLayout(tag_lock_kill_card)
    tag_lock_kill_form.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow)
    tag_lock_kill_form.addRow(window.sec("Tag Lock / Kill"))
    tag_lock_kill_help = QLabel(
        "Use protocol-level hexadecimal Lock Mask and Lock Action values exactly as provided by your tag workflow. "
        "The GUI does not reinterpret or modify these values."
    )
    tag_lock_kill_help.setObjectName("Sub")
    tag_lock_kill_help.setWordWrap(True)
    tag_lock_kill_form.addRow(tag_lock_kill_help)

    tag_lock_kill_form.addRow(window.sec("Lock Tag"))
    window.lock_target_epc = QLineEdit()
    window.lock_target_epc.setPlaceholderText("Target EPC (hex, even number of digits)")
    tag_lock_kill_form.addRow("Target EPC", window.lock_target_epc)
    window.lock_access_password = QLineEdit("00000000")
    window.lock_access_password.setEchoMode(QLineEdit.Password)
    window.lock_access_password.setMaxLength(8)
    window.lock_access_password.setPlaceholderText("8 hexadecimal characters")
    tag_lock_kill_form.addRow("Access Password", window.lock_access_password)
    window.lock_mask = QLineEdit("0000")
    window.lock_mask.setMaxLength(4)
    window.lock_mask.setPlaceholderText("4 hexadecimal characters")
    tag_lock_kill_form.addRow("Lock Mask (hex)", window.lock_mask)
    window.lock_action = QLineEdit("0000")
    window.lock_action.setMaxLength(4)
    window.lock_action.setPlaceholderText("4 hexadecimal characters")
    tag_lock_kill_form.addRow("Lock Action (hex)", window.lock_action)
    lock_actions = QHBoxLayout()
    window.lock_use_selected = QPushButton("Use Selected EPC")
    window.lock_use_selected.clicked.connect(window.use_selected_epc)
    window.lock_tag_btn = QPushButton("Lock Tag")
    window.lock_tag_btn.setObjectName("Primary")
    window.lock_tag_btn.clicked.connect(window.lock_tag)
    window.lock_clear = QPushButton("Clear Lock Fields")
    window.lock_clear.clicked.connect(window.clear_lock_fields)
    lock_actions.addWidget(window.lock_use_selected)
    lock_actions.addWidget(window.lock_tag_btn)
    lock_actions.addWidget(window.lock_clear)
    tag_lock_kill_form.addRow("", lock_actions)

    tag_lock_kill_form.addRow(window.sec("Kill Tag"))
    window.kill_target_epc = QLineEdit()
    window.kill_target_epc.setPlaceholderText("Target EPC (hex, even number of digits)")
    tag_lock_kill_form.addRow("Target EPC", window.kill_target_epc)
    window.kill_password = QLineEdit("00000000")
    window.kill_password.setEchoMode(QLineEdit.Password)
    window.kill_password.setMaxLength(8)
    window.kill_password.setPlaceholderText("8 hexadecimal characters")
    tag_lock_kill_form.addRow("Kill Password", window.kill_password)
    kill_actions = QHBoxLayout()
    window.kill_use_selected = QPushButton("Use Selected EPC")
    window.kill_use_selected.clicked.connect(window.use_selected_epc)
    window.kill_tag_btn = QPushButton("Kill Tag")
    window.kill_tag_btn.setObjectName("Danger")
    window.kill_tag_btn.clicked.connect(window.kill_tag)
    window.kill_clear = QPushButton("Clear Kill Fields")
    window.kill_clear.clicked.connect(window.clear_kill_fields)
    kill_actions.addWidget(window.kill_use_selected)
    kill_actions.addWidget(window.kill_tag_btn)
    kill_actions.addWidget(window.kill_clear)
    tag_lock_kill_form.addRow("", kill_actions)
    tag_lock_kill_layout.addWidget(tag_lock_kill_card)
    tag_lock_kill_layout.addStretch()
    window.stack.addWidget(tag_lock_kill_page)

    # Diagnostics stays visible below the inventory and can be resized by
    # dragging the splitter handle up or down.
    diagnostic_page = QWidget()
    diagnostic_page.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    diagnostic_page.setMinimumHeight(170)
    diagnostic_layout = QVBoxLayout(diagnostic_page)
    diagnostic_layout.setContentsMargins(0, 0, 0, 0)
    diagnostic_layout.addWidget(window.sec("Diagnostics"))
    tabs = QTabWidget()
    tabs.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    window.event = QPlainTextEdit()
    window.event.setReadOnly(True)
    tabs.addTab(window.event, "Event Log")
    window.raw = QPlainTextEdit()
    window.raw.setReadOnly(True)
    tabs.addTab(window.raw, "Raw Serial")
    console = QWidget()
    console_layout = QVBoxLayout(console)
    command_row = QHBoxLayout()
    window.command = QLineEdit()
    window.command.setPlaceholderText("GET_POWER / SET_REGION,01")
    window.command.returnPressed.connect(window.manual)
    send_button = QPushButton("Send")
    send_button.clicked.connect(window.manual)
    command_row.addWidget(window.command)
    command_row.addWidget(send_button)
    console_layout.addLayout(command_row)
    window.responses = QPlainTextEdit()
    window.responses.setReadOnly(True)
    console_layout.addWidget(window.responses)
    tabs.addTab(console, "Command Console")
    about = QWidget()
    about_layout = QVBoxLayout(about)
    about_text = QLabel(
        "Reader information requests are serialized one-at-a-time. Single Poll performs a one-shot read using the existing START/STOP host protocol; Multi Poll keeps inventory running until stopped. Tag filtering is local to the GUI and does not change what the reader captures. Tag Write writes memory data using the current EPC as the selection filter. The STM32 firmware performs up to three write attempts per click. Serial RX is line-buffered so split USB packets are reconstructed before parsing."
    )
    about_text.setWordWrap(True)
    about_layout.addWidget(about_text)
    about_layout.addStretch()
    tabs.addTab(about, "About")
    diagnostic_layout.addWidget(tabs)

    window.content_split = QSplitter(Qt.Vertical)
    window.content_split.setChildrenCollapsible(False)
    window.content_split.setHandleWidth(8)
    window.content_split.addWidget(window.main_split)
    window.content_split.addWidget(diagnostic_page)
    window.content_split.setStretchFactor(0, 4)
    window.content_split.setStretchFactor(1, 1)
    window.content_split.setSizes([520, 220])
    window.content_layout.addWidget(window.content_split)

    window.select_feature(0)
